In [27]:
import pandas as pd
import numpy as np

In [28]:
data = pd.read_csv('houses_to_rent.csv', index_col=False)

In [39]:
print(data.shape)
data

(6080, 13)

,city,area,rooms,bathroom,parking spaces,floor,animal,furniture,hoa,rent amount,property tax,fire insurance,total
0,1,45,1,1,0,1,0,0,300,1340,0,17,1657
1,1,80,2,2,1,12,1,0,1200,10000,109,127,11440
2,1,130,3,1,1,0,1,0,0,5600,0,85,5685
3,1,62,3,1,1,8,1,0,750,1260,59,16,2085
4,1,180,2,1,0,0,1,0,0,2300,188,35,2523
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6075,1,90,3,2,2,3,1,0,1100,2450,117,32,3699
6076,1,50,1,1,0,11,1,1,390,3698,7,47,4142
6077,1,300,4,4,5,11,1,0,3150,11000,1225,140,15520
6078,1,70,2,1,1,7,1,0,500,1300,48,17,1865
6079,1,260,4,5,5,6,1,0,3000,12500,1667,159,17330

In [30]:
### удаляем лишний столбец
data.drop(data.columns[0], axis=1, inplace=True)

In [31]:
### Заменяем пустые ячейки - нулями
data['floor'].replace(to_replace='-', value=0, inplace=True)

In [32]:
### Заменяем строчные данные на числовые (animal)
data['animal'].replace(to_replace='not acept', value=0, inplace=True)
data['animal'].replace(to_replace='acept', value=1, inplace=True)

In [33]:
### Заменяем строчные данные на числовые (furniture)
data['furniture'].replace(to_replace='not furnished', value=0, inplace=True)
data['furniture'].replace(to_replace='furnished', value=1, inplace=True)

In [34]:
### Выкидываем лишние символы ('R', '$', ',')
for col in ['hoa', 'rent amount', 'property tax', 'fire insurance', 'total']:
    data[col].replace(to_replace='R\$', value='', regex=True, inplace=True)
    data[col].replace(to_replace=',', value='', regex=True, inplace=True)

In [35]:
### Заменяем значения ячеек Sem info, Incluso на 0 
data['hoa'].replace(to_replace='Sem info', value='0', inplace=True)
data['hoa'].replace(to_replace='Incluso', value='0', inplace=True)
data['property tax'].replace(to_replace='Incluso', value='0', inplace=True)

In [36]:
data = data.astype(dtype=np.int64)

In [38]:
data = data.sample(frac=1).reset_index(drop=True)

In [42]:
y = data['city']
X = data.drop('city', axis=1)

### Готовим данные для модели

In [44]:
from sklearn.model_selection import train_test_split

In [45]:
from sklearn.preprocessing import MinMaxScaler

In [46]:
### Упрощаяем вид данных в промежутке 0-9 с помощью MinMaxScaler()
scaler = MinMaxScaler()
scaler.fit(X)
X = scaler.transform(X)

In [48]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11
0,0.001423,0.000000,0.000000,0.000000,0.010101,0.0,0.0,0.001364,0.020637,0.000000,0.020772,0.002680
1,0.002846,0.111111,0.111111,0.083333,0.121212,1.0,0.0,0.005455,0.214895,0.000298,0.183976,0.028975
2,0.004879,0.222222,0.000000,0.083333,0.000000,1.0,0.0,0.000000,0.116196,0.000000,0.121662,0.013507
3,0.002114,0.222222,0.000000,0.083333,0.080808,1.0,0.0,0.003409,0.018843,0.000161,0.019288,0.003830
4,0.006912,0.111111,0.000000,0.000000,0.000000,1.0,0.0,0.000000,0.042171,0.000513,0.047478,0.005008
...,...,...,...,...,...,...,...,...,...,...,...,...
6075,0.003253,0.222222,0.111111,0.166667,0.030303,1.0,0.0,0.005000,0.045536,0.000319,0.043027,0.008168
6076,0.001626,0.000000,0.000000,0.000000,0.111111,1.0,1.0,0.001773,0.073531,0.000019,0.065282,0.009359
6077,0.011791,0.333333,0.333333,0.416667,0.111111,1.0,0.0,0.014318,0.237326,0.003344,0.203264,0.039942
6078,0.002439,0.111111,0.000000,0.083333,0.070707,1.0,0.0,0.002273,0.019740,0.000131,0.020772,0.003239
6079,0.010164,0.333333,0.444444,0.416667,0.060606,1.0,0.0,0.013636,0.270974,0.004551,0.231454,0.044807

In [49]:
### Делим данные на train и test (80% и 20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8)

### Будем использовать три модели: Логистическая регрессия, Машина опорных векторов, Нейронные сети

In [52]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier

In [54]:
log_model = LogisticRegression(penalty='l2', verbose=1)
svm_model = SVC(kernel='rbf', verbose=1)
nn_model = MLPClassifier(hidden_layer_sizes=(16, 16), activation='relu', solver='adam', verbose=1)

In [55]:
log_model.fit(X_train, y_train)
svm_model.fit(X_train, y_train)
nn_model.fit(X_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished

[LibSVM]Iteration 1, loss = 0.69794130
Iteration 2, loss = 0.63156845
Iteration 3, loss = 0.59771332
Iteration 4, loss = 0.56663206
Iteration 5, loss = 0.52920771
Iteration 6, loss = 0.49165569
Iteration 7, loss = 0.44310041
Iteration 8, loss = 0.41004111
Iteration 9, loss = 0.40195705
Iteration 10, loss = 0.39916883
Iteration 11, loss = 0.39718550
Iteration 12, loss = 0.39519632
Iteration 13, loss = 0.39335119
Iteration 14, loss = 0.39168798
Iteration 15, loss = 0.39009784
Iteration 16, loss = 0.38876281
Iteration 17, loss = 0.38765504
Iteration 18, loss = 0.38653607
Iteration 19, loss = 0.38549161
Iteration 20, loss = 0.38456423
Iteration 21, loss = 0.38366477
Iteration 22, loss = 0.38305490
Iteration 23, loss = 0.38212159
Iteration 24, loss = 0.38156651
Iteration 25, loss = 0.38129580
Iteration 26, loss = 0.38062664
Iteration 27, loss = 0.37933959
Iteration 28, loss = 0.37873155
Iteration 29, loss = 0.37798389
Iteration 30, loss = 0.37739225
Iteration 31, loss = 0.37678455
Iteration 32, loss = 0.37620014
Iteration 33, loss = 0.37517624
Iteration 34, loss = 0.37444045
Iteration 35, loss = 0.37374392
Iteration 36, loss = 0.37314361
Iteration 37, loss = 0.37207787
Iteration 38, loss = 0.37115547
Iteration 39, loss = 0.37044169
Iteration 40, loss = 0.36974062
Iteration 41, loss = 0.36892270
Iteration 42, loss = 0.36818205
Iteration 43, loss = 0.36793943
Iteration 44, loss = 0.36683554
Iteration 45, loss = 0.36617316
Iteration 46, loss = 0.36562843
Iteration 47, loss = 0.36490699
Iteration 48, loss = 0.36423640
Iteration 49, loss = 0.36386468
Iteration 50, loss = 0.36318454
Iteration 51, loss = 0.36287050
Iteration 52, loss = 0.36268922
Iteration 53, loss = 0.36161247
Iteration 54, loss = 0.36109864
Iteration 55, loss = 0.36070574
Iteration 56, loss = 0.36033086
Iteration 57, loss = 0.35979954
Iteration 58, loss = 0.35960775
Iteration 59, loss = 0.35885680
Iteration 60, loss = 0.35856378
Iteration 61, loss = 0.35807196
Iteration 62, loss = 0.35769920
Iteration 63, loss = 0.35728275
Iteration 64, loss = 0.35686103
Iteration 65, loss = 0.35640858
Iteration 66, loss = 0.35589962
Iteration 67, loss = 0.35557764
Iteration 68, loss = 0.35496694
Iteration 69, loss = 0.35449297
Iteration 70, loss = 0.35414302
Iteration 71, loss = 0.35364042
Iteration 72, loss = 0.35312468
Iteration 73, loss = 0.35256650
Iteration 74, loss = 0.35206425
Iteration 75, loss = 0.35232432
Iteration 76, loss = 0.35114222
Iteration 77, loss = 0.35093329
Iteration 78, loss = 0.35025057
Iteration 79, loss = 0.35117312
Iteration 80, loss = 0.34945777
Iteration 81, loss = 0.34882673
Iteration 82, loss = 0.34904868
Iteration 83, loss = 0.34808850
Iteration 84, loss = 0.34742081
Iteration 85, loss = 0.34734766
Iteration 86, loss = 0.34668748
Iteration 87, loss = 0.34598350
Iteration 88, loss = 0.34541000
Iteration 89, loss = 0.34467742
Iteration 90, loss = 0.34406222
Iteration 91, loss = 0.34359754
Iteration 92, loss = 0.34397587
Iteration 93, loss = 0.34271160
Iteration 94, loss = 0.34199000
Iteration 95, loss = 0.34173957
Iteration 96, loss = 0.34094042
Iteration 97, loss = 0.34058927
Iteration 98, loss = 0.33979610
Iteration 99, loss = 0.33991928
Iteration 100, loss = 0.33891943
Iteration 101, loss = 0.33831727
Iteration 102, loss = 0.33779434
Iteration 103, loss = 0.33749352
Iteration 104, loss = 0.33702956
Iteration 105, loss = 0.33653299
Iteration 106, loss = 0.33644638
Iteration 107, loss = 0.33580917
Iteration 108, loss = 0.33478421
Iteration 109, loss = 0.33487646
Iteration 110, loss = 0.33439887
Iteration 111, loss = 0.33358024
Iteration 112, loss = 0.33321931
Iteration 113, loss = 0.33255484
Iteration 114, loss = 0.33252575
Iteration 115, loss = 0.33184257
Iteration 116, loss = 0.33115233
Iteration 117, loss = 0.33085468
Iteration 118, loss = 0.33056817
Iteration 119, loss = 0.33029933
Iteration 120, loss = 0.33006966
Iteration 121, loss = 0.32975282
Iteration 122, loss = 0.32896415
Iteration 123, loss = 0.32860274
Iteration 124, loss = 0.32867290
Iteration 125, loss = 0.32815104
Iteration 126, loss = 0.32743745
Iteration 127, loss = 0.32768120
Iteration 128, loss = 0.32718852
Iteration 129, loss = 0.32694800
Iteration 130, loss = 0.32641258
Iteration 131, loss = 0.32594724
Iteration 132, loss = 0.32564944
Iteration 133, loss = 0.32540790
Iteration 134, loss = 0.32526855
Iteration 135, loss = 0.32468369
Iteration 136, loss = 0.32440836
Iteration 137, loss = 0.32456305
Iteration 138, loss = 0.32371637
Iteration 139, loss = 0.32380420
Iteration 140, loss = 0.32349192
Iteration 141, loss = 0.32296306
Iteration 142, loss = 0.32274165
Iteration 143, loss = 0.32305584
Iteration 144, loss = 0.32234066
Iteration 145, loss = 0.32197987
Iteration 146, loss = 0.32229319
Iteration 147, loss = 0.32298854
Iteration 148, loss = 0.32103241
Iteration 149, loss = 0.32068283
Iteration 150, loss = 0.32057095
Iteration 151, loss = 0.32036489
Iteration 152, loss = 0.32012917
Iteration 153, loss = 0.31962597
Iteration 154, loss = 0.31948853
Iteration 155, loss = 0.31901696
Iteration 156, loss = 0.31875987
Iteration 157, loss = 0.31878826
Iteration 158, loss = 0.31839269
Iteration 159, loss = 0.31814008
Iteration 160, loss = 0.31804911
Iteration 161, loss = 0.31852474
Iteration 162, loss = 0.31746068
Iteration 163, loss = 0.31712169
Iteration 164, loss = 0.31704460
Iteration 165, loss = 0.31697316
Iteration 166, loss = 0.31644503
Iteration 167, loss = 0.31620339
Iteration 168, loss = 0.31590765
Iteration 169, loss = 0.31580134
Iteration 170, loss = 0.31562342
Iteration 171, loss = 0.31544320
Iteration 172, loss = 0.31520069
Iteration 173, loss = 0.31475351
Iteration 174, loss = 0.31480645
Iteration 175, loss = 0.31419935
Iteration 176, loss = 0.31426644
Iteration 177, loss = 0.31377900
Iteration 178, loss = 0.31369627
Iteration 179, loss = 0.31338137
Iteration 180, loss = 0.31328875
Iteration 181, loss = 0.31284028
Iteration 182, loss = 0.31269685
Iteration 183, loss = 0.31256723
Iteration 184, loss = 0.31252701
Iteration 185, loss = 0.31195157
Iteration 186, loss = 0.31189172
Iteration 187, loss = 0.31204808
Iteration 188, loss = 0.31169734
Iteration 189, loss = 0.31116803
Iteration 190, loss = 0.31081607
Iteration 191, loss = 0.31101960
Iteration 192, loss = 0.31120717
Iteration 193, loss = 0.31032426
Iteration 194, loss = 0.31009568
Iteration 195, loss = 0.31012328
Iteration 196, loss = 0.30983483
Iteration 197, loss = 0.30982725
Iteration 198, loss = 0.30975807
Iteration 199, loss = 0.30925816
Iteration 200, loss = 0.30926809

c:\users\user\appdata\local\programs\python\python39\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

MLPClassifier(hidden_layer_sizes=(16, 16), verbose=1)

In [56]:
print(log_model.score(X_test, y_test))
print(svm_model.score(X_test, y_test))
print(nn_model.score(X_test, y_test))

0.8824013157894737
0.8824013157894737
0.9013157894736842

In [58]:
from sklearn.metrics import f1_score

In [59]:
log_pred = log_model.predict(X_test)
svm_pred = svm_model.predict(X_test)
nn_pred = nn_model.predict(X_test)

In [63]:
print(f1_score(log_pred, y_test))
print(f1_score(svm_pred, y_test))
print(f1_score(nn_pred, y_test))

0.9375273044997816
0.9375273044997816
0.9461400359066428